# This is a basic workflow to help you get started with Actions

name: Publish a Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@princetonuniversityoit'

      - run: npm install

      - run: npm run build-lib

      - uses: JS-DevTools/npm-publish@v1
        with:
            package: "./dist/design-system-angular/package.json"
            token: ${{ secrets.NPM_TOKEN }}
            access: public

      - run: npm run build-site

      - run: npm run build-docsite-prod

      - run: npm run docs:json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
